-- V1__Create_Inventory_Table.sql

-- Create the Inventory table
CREATE TABLE Inventory (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           productId BIGINT NOT NULL,
                           quantity INTEGER NOT NULL
);

-- Create the InventoryMovement table (assuming it's similar to Inventory)
CREATE TABLE InventoryMovement (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   inventory_id BIGINT,
                                   quantityChange INTEGER NOT NULL,
                                   movementType VARCHAR(4) NOT NULL,
                                   movementDate TIMESTAMP NOT NULL,
                                   FOREIGN KEY (inventory_id) REFERENCES Inventory(id) ON DELETE CASCADE
);


